# creation rules are evaluated sequentially, the first match wins
creation_rules:
     # upon creation of a file that matches the pattern *.dev.yaml,
     #KMS set A is used
     - kms: "arn:aws:kms:us-east-2:852198238540:key/24d55211-6230-4fdc-b9fe-f48eecc3fc5b"